account/urls.py
from django.urls import path
from .views import (
	LoginView, ValidateView,
	AddInviteView, ListInviteView,
	AccountView, LogoutView,
	EditView, select_lang,
)

app_name = 'account'

urlpatterns = [
	path('login/', LoginView.as_view(), name='login'),
	path('validate/', ValidateView.as_view(), name='validate'),
	path('logout/', LogoutView, name='logout'),
	path('edit/', EditView.as_view(), name='edit'),
	path('add_invite/', AddInviteView.as_view(), name='add_invite'),
	path('list_invite/', ListInviteView.as_view(), name='list_invite'),
	path('<str:code>/', select_lang, name='select_lang'),
	path('', AccountView, name='account'),
]

api/urls.py
from django.urls import path
from .views import LoginValidateCreateAPIView, AccountRetrieveUpdateAPIView

app_name = 'api'

urlpatterns = [
	path('login/', LoginValidateCreateAPIView.as_view(), name='login'),
	path('account/', AccountRetrieveUpdateAPIView.as_view(), name='account'),
]

invite_django/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework.authtoken import views

urlpatterns = [
	path('admin/', admin.site.urls),
	path('api/', include('api.urls')),
	path('', include('account.urls')),
]

templates/layout/basic.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% translate "Main" %}{% endblock %}</title>

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body>
	<nav class="navbar navbar-light bg-light">
		<div class="container">
			<a class="navbar-brand h1 my-0" href="/">{% translate "Basic Referral System" %}{% if user.get_username %} ({{user.get_username}}){% endif %}</a>
			<a class="nav-link active me-auto" aria-current="page" href={% url 'account:account' %}>{% if user.is_authenticated %}{% translate "Account" %}{% endif %}</a>
			{% get_current_language as LANGUAGE_CODE %}
			{% get_available_languages as LANGUAGES %}
			{% get_language_info_list for LANGUAGES as languages %}
			<li class="nav-item dropdown list-unstyled">
				<a class="nav-link dropdown-toggle fw-bold" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">{% translate "Language" %}</a>
				<ul class="dropdown-menu ">
					{% for language in languages %}
					<li><a class="dropdown-item {% if language.code == LANGUAGE_CODE %} active {% endif %}" href="/{{ language.code }}/">{{ language.name_local }}</a></li>
					{% endfor %}
				</ul>
			</li>
			{% if user.is_authenticated %}
				<a type="button" class="btn btn-lg text-nowrap btn-danger"	href={% url 'account:logout' %}>{% translate "Exit" %}</a>
			{% else %}
				<a type="button" class="btn btn-lg text-nowrap btn-primary"	href= {% url 'account:login' %}>{% translate "Login" %}</a>
			{% endif %}

		</div>
	</nav>
	<div class="toast-container position-absolute top-0 end-0 p-3">
		{% if messages %}
			<div class="toast fade show" role="alert" aria-live="assertive" aria-atomic="true">
			{% for message in messages %}
				<div class="toast-header">
				{% if message.extra_tags %}<strong class="me-auto">{{ message.extra_tags }}</strong>{% endif %}
				<button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Закрыть"></button>
				</div>
			<div class="toast-body">{{ message }}</div>
			{% endfor %}
		</div>
		{% endif %}
	</div>
	{% block content %}

	{% endblock %}
</body>
</html>